site_name: hierarchical_loss

repo_url: https://github.com/csbrown-noaa/hierarchical_loss

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
  markdown_extensions:
    - markdown.extensions.admonition
    - markdown.extensions.codehilite
    - pymdownx.superfences
    - pymdownx.arithmatex:
        generic: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: README.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Code Reference:
      - COCO utilities: api/coco_utils.md
      - Hierarchy paths utilities: api/path_utils.md
      - Generic tree utilities: api/tree_utils.md
      - WORMS utilities: api/worms_utils.md
      - Visualization utilities: api/viz_utils.md
      - General utilities: api/utils.md
      - Hierarchy tensor utilities: api/hierarchy_tensor_utils.md
      - Hierarchical loss: api/hierarchical_loss.md
      - Hierarchy caching class: api/hierarchy.md

